server: 
    port: 8484
spring:
  application:
    name: config-server
  cloud: 
    config:
        server:
            git: 
              uri: https://github.com/Dan-Elioth/FBakend-Distribuidas.git
              search-paths: config-data
              username: Dan
              password: 123
              default-label: main
  security:
    user:
      name: root
      password: s3cr3t